### ISSUE TITLE
Inability to work with cloud using OwnCloudBasicCredentials only (not android.accounts.Account)

### ISSUE THREAD

**Issue by Den-Rimus** [owncloud/android-library#257]
When executing operations (e.g. `ReadRemoteFolderOperation`) - logic always ends up attempting to use `mAccount.getSavedAccount()` inside client, which is always `null` for `OwnCloudAccount` instance if constructor `public OwnCloudAccount(Uri baseUri, OwnCloudCredentials credentials)` used for creation. Even your own sample app does not work.

Is it even possible to work with plain username&password pair?

P. S.: is this even actual library to attempt to use for accessing ownCloud? It really looks like you gave up on implementing it in the middle of development and somehow gave it 'stable' status (at least I'm trying to use that branch).

**Comment by michaelstingl** [comment]
@Den-Rimus please check master. 

Here you can find an overview of the branches:
https://github.com/owncloud/android-library/network

For stable, maybe check the releases:
https://github.com/owncloud/android-library/releases

**Comment by michaelstingl** [comment]
@davigonz update docs/README about stable?

**Comment by Den-Rimus** [comment]
> @Den-Rimus please check master.

Same. It cannot work.

**Comment by davigonz** [comment]
Let me have a look...

**Comment by davigonz** [comment]
@Den-Rimus Yes, I can reproduce what you say and it should be fixed, this library suffered significant changes when we [switched to a new network library ](https://github.com/owncloud/android-library/issues/51) so it's normal that this kind of things appear, thanks for reporting it.

@michaelstingl since ownCloudClient and ownCloudAccount are much related with [authentication](https://github.com/owncloud/android/issues/2608) and that's the next topic in terms of new architecture, I would address this issue there, what do you think?

**Comment by michaelstingl** [comment]
> @michaelstingl since ownCloudClient and ownCloudAccount are much related with [authentication](https://github.com/owncloud/android/issues/2608) and that's the next topic in terms of new architecture, I would address this issue there, what do you think?

👍

**Comment by lawer** [comment]
Any news on this issue? it fails on me.

**Comment by JuancaG05** [comment]
Hi @lawer, can you still reproduce this? Let us know, please! 👍
